[ROR 1.25.0][RORDEV-365] auth_key_pbkdf2 description
beshu-tech/readonlyrest-docs pull request #70
Opened 2020-10-17 09:55 UTC by coutoPL

[don't merge before release of ROR 1.25.0]

2020-10-18 16:11 UTC, coutoPL commented
ref: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/651

2020-10-23 08:25 UTC, sscarduzio requested changes
Just a few small corrections.

2020-10-23 08:25 UTC, sscarduzio commented on elasticsearch.md
> +hashed secret.
in the example above, `admin` is the username, and `...` is the hashed password.

2020-10-23 08:25 UTC, sscarduzio commented on elasticsearch.md
> +it, so during hash generation user has to take into consideration
during the hash generation process, the user has to take in consideration the following ...

2020-10-23 08:25 UTC, sscarduzio commented on elasticsearch.md
> +The hash can be calculated using [this calculator](https://8gwifi.org/pbkdf.jsp) (notice that salt have to base Base64 encoded).
notice that the salt has to be Base64 encoded

2020-11-01 09:49 UTC, merged