[RORDEV-437] Added info about CB in ldap
beshu-tech/readonlyrest-docs pull request #93
Opened 2021-05-11 20:38 UTC by pielas

2021-05-12 11:02 UTC, sscarduzio requested changes
Just a few minor tweaks. Thank you.

2021-05-12 11:02 UTC, sscarduzio commented on elasticsearch.md
> +* `reset_duration` defines how long circuit breaker will block requests until sending one test request.
.... how long the circuit breaker feature will block the incoming requests before starting to send one test request. to the LDAP server.

2021-05-12 18:43 UTC, coutoPL requested changes

2021-05-12 18:43 UTC, coutoPL commented on elasticsearch.md
> +The LDAP connector is equipped by default with the circuit breaker functionality. The circuit breaker disables sending new requests to the server when it doesn't respond properly. After receiving con
I'd link wiki somewhere here: https://en.wikipedia.org/wiki/Circuit_breaker_design_pattern

2021-05-13 18:33 UTC, coutoPL approved these changes

2021-05-14 10:07 UTC, sscarduzio approved these changes

2021-05-14 10:07 UTC, merged